apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api-deployment
  template:
    metadata:
      labels:
        app: weather-api-deployment
    spec:
      containers:
        - name: weather-api-deployment
          image: weatherapi-dockerfile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api-deployment-svc
spec:
  selector:
    app: weather-api-deployment
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort